CREATE TABLE IF NOT EXISTS TIMESTAMPS_TASKS_CREATED(
        ID CHAR(40) NOT NULL,
        CREATED TIMESTAMP NOT NULL,
        PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TIMESTAMPS_TASKS_COMPLETED(
        ID CHAR(40) NOT NULL,
        COMPLETED TIMESTAMP NOT NULL,
        PRIMARY KEY (ID)
);